
services:
  catalogdb:
    image: postgres:latest

  basketdb:
    image: postgres:latest

  redis:
    image: redis:latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

  dicount.grpc:
    image: ${DOCKER_REGISTRY-}dicountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Dicount.Grpc/Dockerfile

volumes:
  postgres_catalogdb:
  postgres_basketdb:




